# Generated by Django 3.0.4 on 2020-04-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200422_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='second_name',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
