# Generated by Django 3.0.4 on 2020-04-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200423_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
